version: 2.1

orbs:
  python: circleci/python@2.1.1
  aws-sam-serverless: circleci/aws-sam-serverless@6.0.1
  aws-cli: circleci/aws-cli@4.0

jobs:
  build_and_test: # this can be any name you choose
    executor: python/default # use the default executor defined within the orb
    steps:
      - checkout # checkout source code
      - python/install-packages:
          app-dir: hello_world
          pkg-manager: pip
      - run:
          name: Run tests
          command: |
            pip install -r tests/requirements.txt
            python -m pytest tests/unit/test_handler.py
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
  deploy:
    executor: aws-cli/default
    steps: 
      - aws-cli/setup:
          profile_name: default
      - run:
          command: aws s3 ls
          name: deploy
          environment:
            AWS_DEFAULT_REGION: us-east-1

workflows:
  build_test_deploy:
    jobs:
      - build_and_test
      - deploy:
          requires:
            - build_and_test
          context: awsdeploy